// generated by go generate; DO NOT EDIT.

package sdlcolornames

import "github.com/veandco/go-sdl2/sdl"

// Map contains named colors defined in the SVG 1.1 spec.
var Map = map[string]sdl.Color{
	"aliceblue":            sdl.Color{0xf0, 0xf8, 0xff, 0xff}, // rgb(240, 248, 255)
	"antiquewhite":         sdl.Color{0xfa, 0xeb, 0xd7, 0xff}, // rgb(250, 235, 215)
	"aqua":                 sdl.Color{0x00, 0xff, 0xff, 0xff}, // rgb(0, 255, 255)
	"aquamarine":           sdl.Color{0x7f, 0xff, 0xd4, 0xff}, // rgb(127, 255, 212)
	"azure":                sdl.Color{0xf0, 0xff, 0xff, 0xff}, // rgb(240, 255, 255)
	"beige":                sdl.Color{0xf5, 0xf5, 0xdc, 0xff}, // rgb(245, 245, 220)
	"bisque":               sdl.Color{0xff, 0xe4, 0xc4, 0xff}, // rgb(255, 228, 196)
	"black":                sdl.Color{0x00, 0x00, 0x00, 0xff}, // rgb(0, 0, 0)
	"blanchedalmond":       sdl.Color{0xff, 0xeb, 0xcd, 0xff}, // rgb(255, 235, 205)
	"blue":                 sdl.Color{0x00, 0x00, 0xff, 0xff}, // rgb(0, 0, 255)
	"blueviolet":           sdl.Color{0x8a, 0x2b, 0xe2, 0xff}, // rgb(138, 43, 226)
	"brown":                sdl.Color{0xa5, 0x2a, 0x2a, 0xff}, // rgb(165, 42, 42)
	"burlywood":            sdl.Color{0xde, 0xb8, 0x87, 0xff}, // rgb(222, 184, 135)
	"cadetblue":            sdl.Color{0x5f, 0x9e, 0xa0, 0xff}, // rgb(95, 158, 160)
	"chartreuse":           sdl.Color{0x7f, 0xff, 0x00, 0xff}, // rgb(127, 255, 0)
	"chocolate":            sdl.Color{0xd2, 0x69, 0x1e, 0xff}, // rgb(210, 105, 30)
	"coral":                sdl.Color{0xff, 0x7f, 0x50, 0xff}, // rgb(255, 127, 80)
	"cornflowerblue":       sdl.Color{0x64, 0x95, 0xed, 0xff}, // rgb(100, 149, 237)
	"cornsilk":             sdl.Color{0xff, 0xf8, 0xdc, 0xff}, // rgb(255, 248, 220)
	"crimson":              sdl.Color{0xdc, 0x14, 0x3c, 0xff}, // rgb(220, 20, 60)
	"cyan":                 sdl.Color{0x00, 0xff, 0xff, 0xff}, // rgb(0, 255, 255)
	"darkblue":             sdl.Color{0x00, 0x00, 0x8b, 0xff}, // rgb(0, 0, 139)
	"darkcyan":             sdl.Color{0x00, 0x8b, 0x8b, 0xff}, // rgb(0, 139, 139)
	"darkgoldenrod":        sdl.Color{0xb8, 0x86, 0x0b, 0xff}, // rgb(184, 134, 11)
	"darkgray":             sdl.Color{0xa9, 0xa9, 0xa9, 0xff}, // rgb(169, 169, 169)
	"darkgreen":            sdl.Color{0x00, 0x64, 0x00, 0xff}, // rgb(0, 100, 0)
	"darkgrey":             sdl.Color{0xa9, 0xa9, 0xa9, 0xff}, // rgb(169, 169, 169)
	"darkkhaki":            sdl.Color{0xbd, 0xb7, 0x6b, 0xff}, // rgb(189, 183, 107)
	"darkmagenta":          sdl.Color{0x8b, 0x00, 0x8b, 0xff}, // rgb(139, 0, 139)
	"darkolivegreen":       sdl.Color{0x55, 0x6b, 0x2f, 0xff}, // rgb(85, 107, 47)
	"darkorange":           sdl.Color{0xff, 0x8c, 0x00, 0xff}, // rgb(255, 140, 0)
	"darkorchid":           sdl.Color{0x99, 0x32, 0xcc, 0xff}, // rgb(153, 50, 204)
	"darkred":              sdl.Color{0x8b, 0x00, 0x00, 0xff}, // rgb(139, 0, 0)
	"darksalmon":           sdl.Color{0xe9, 0x96, 0x7a, 0xff}, // rgb(233, 150, 122)
	"darkseagreen":         sdl.Color{0x8f, 0xbc, 0x8f, 0xff}, // rgb(143, 188, 143)
	"darkslateblue":        sdl.Color{0x48, 0x3d, 0x8b, 0xff}, // rgb(72, 61, 139)
	"darkslategray":        sdl.Color{0x2f, 0x4f, 0x4f, 0xff}, // rgb(47, 79, 79)
	"darkslategrey":        sdl.Color{0x2f, 0x4f, 0x4f, 0xff}, // rgb(47, 79, 79)
	"darkturquoise":        sdl.Color{0x00, 0xce, 0xd1, 0xff}, // rgb(0, 206, 209)
	"darkviolet":           sdl.Color{0x94, 0x00, 0xd3, 0xff}, // rgb(148, 0, 211)
	"deeppink":             sdl.Color{0xff, 0x14, 0x93, 0xff}, // rgb(255, 20, 147)
	"deepskyblue":          sdl.Color{0x00, 0xbf, 0xff, 0xff}, // rgb(0, 191, 255)
	"dimgray":              sdl.Color{0x69, 0x69, 0x69, 0xff}, // rgb(105, 105, 105)
	"dimgrey":              sdl.Color{0x69, 0x69, 0x69, 0xff}, // rgb(105, 105, 105)
	"dodgerblue":           sdl.Color{0x1e, 0x90, 0xff, 0xff}, // rgb(30, 144, 255)
	"firebrick":            sdl.Color{0xb2, 0x22, 0x22, 0xff}, // rgb(178, 34, 34)
	"floralwhite":          sdl.Color{0xff, 0xfa, 0xf0, 0xff}, // rgb(255, 250, 240)
	"forestgreen":          sdl.Color{0x22, 0x8b, 0x22, 0xff}, // rgb(34, 139, 34)
	"fuchsia":              sdl.Color{0xff, 0x00, 0xff, 0xff}, // rgb(255, 0, 255)
	"gainsboro":            sdl.Color{0xdc, 0xdc, 0xdc, 0xff}, // rgb(220, 220, 220)
	"ghostwhite":           sdl.Color{0xf8, 0xf8, 0xff, 0xff}, // rgb(248, 248, 255)
	"gold":                 sdl.Color{0xff, 0xd7, 0x00, 0xff}, // rgb(255, 215, 0)
	"goldenrod":            sdl.Color{0xda, 0xa5, 0x20, 0xff}, // rgb(218, 165, 32)
	"gray":                 sdl.Color{0x80, 0x80, 0x80, 0xff}, // rgb(128, 128, 128)
	"green":                sdl.Color{0x00, 0x80, 0x00, 0xff}, // rgb(0, 128, 0)
	"greenyellow":          sdl.Color{0xad, 0xff, 0x2f, 0xff}, // rgb(173, 255, 47)
	"grey":                 sdl.Color{0x80, 0x80, 0x80, 0xff}, // rgb(128, 128, 128)
	"honeydew":             sdl.Color{0xf0, 0xff, 0xf0, 0xff}, // rgb(240, 255, 240)
	"hotpink":              sdl.Color{0xff, 0x69, 0xb4, 0xff}, // rgb(255, 105, 180)
	"indianred":            sdl.Color{0xcd, 0x5c, 0x5c, 0xff}, // rgb(205, 92, 92)
	"indigo":               sdl.Color{0x4b, 0x00, 0x82, 0xff}, // rgb(75, 0, 130)
	"ivory":                sdl.Color{0xff, 0xff, 0xf0, 0xff}, // rgb(255, 255, 240)
	"khaki":                sdl.Color{0xf0, 0xe6, 0x8c, 0xff}, // rgb(240, 230, 140)
	"lavender":             sdl.Color{0xe6, 0xe6, 0xfa, 0xff}, // rgb(230, 230, 250)
	"lavenderblush":        sdl.Color{0xff, 0xf0, 0xf5, 0xff}, // rgb(255, 240, 245)
	"lawngreen":            sdl.Color{0x7c, 0xfc, 0x00, 0xff}, // rgb(124, 252, 0)
	"lemonchiffon":         sdl.Color{0xff, 0xfa, 0xcd, 0xff}, // rgb(255, 250, 205)
	"lightblue":            sdl.Color{0xad, 0xd8, 0xe6, 0xff}, // rgb(173, 216, 230)
	"lightcoral":           sdl.Color{0xf0, 0x80, 0x80, 0xff}, // rgb(240, 128, 128)
	"lightcyan":            sdl.Color{0xe0, 0xff, 0xff, 0xff}, // rgb(224, 255, 255)
	"lightgoldenrodyellow": sdl.Color{0xfa, 0xfa, 0xd2, 0xff}, // rgb(250, 250, 210)
	"lightgray":            sdl.Color{0xd3, 0xd3, 0xd3, 0xff}, // rgb(211, 211, 211)
	"lightgreen":           sdl.Color{0x90, 0xee, 0x90, 0xff}, // rgb(144, 238, 144)
	"lightgrey":            sdl.Color{0xd3, 0xd3, 0xd3, 0xff}, // rgb(211, 211, 211)
	"lightpink":            sdl.Color{0xff, 0xb6, 0xc1, 0xff}, // rgb(255, 182, 193)
	"lightsalmon":          sdl.Color{0xff, 0xa0, 0x7a, 0xff}, // rgb(255, 160, 122)
	"lightseagreen":        sdl.Color{0x20, 0xb2, 0xaa, 0xff}, // rgb(32, 178, 170)
	"lightskyblue":         sdl.Color{0x87, 0xce, 0xfa, 0xff}, // rgb(135, 206, 250)
	"lightslategray":       sdl.Color{0x77, 0x88, 0x99, 0xff}, // rgb(119, 136, 153)
	"lightslategrey":       sdl.Color{0x77, 0x88, 0x99, 0xff}, // rgb(119, 136, 153)
	"lightsteelblue":       sdl.Color{0xb0, 0xc4, 0xde, 0xff}, // rgb(176, 196, 222)
	"lightyellow":          sdl.Color{0xff, 0xff, 0xe0, 0xff}, // rgb(255, 255, 224)
	"lime":                 sdl.Color{0x00, 0xff, 0x00, 0xff}, // rgb(0, 255, 0)
	"limegreen":            sdl.Color{0x32, 0xcd, 0x32, 0xff}, // rgb(50, 205, 50)
	"linen":                sdl.Color{0xfa, 0xf0, 0xe6, 0xff}, // rgb(250, 240, 230)
	"magenta":              sdl.Color{0xff, 0x00, 0xff, 0xff}, // rgb(255, 0, 255)
	"maroon":               sdl.Color{0x80, 0x00, 0x00, 0xff}, // rgb(128, 0, 0)
	"mediumaquamarine":     sdl.Color{0x66, 0xcd, 0xaa, 0xff}, // rgb(102, 205, 170)
	"mediumblue":           sdl.Color{0x00, 0x00, 0xcd, 0xff}, // rgb(0, 0, 205)
	"mediumorchid":         sdl.Color{0xba, 0x55, 0xd3, 0xff}, // rgb(186, 85, 211)
	"mediumpurple":         sdl.Color{0x93, 0x70, 0xdb, 0xff}, // rgb(147, 112, 219)
	"mediumseagreen":       sdl.Color{0x3c, 0xb3, 0x71, 0xff}, // rgb(60, 179, 113)
	"mediumslateblue":      sdl.Color{0x7b, 0x68, 0xee, 0xff}, // rgb(123, 104, 238)
	"mediumspringgreen":    sdl.Color{0x00, 0xfa, 0x9a, 0xff}, // rgb(0, 250, 154)
	"mediumturquoise":      sdl.Color{0x48, 0xd1, 0xcc, 0xff}, // rgb(72, 209, 204)
	"mediumvioletred":      sdl.Color{0xc7, 0x15, 0x85, 0xff}, // rgb(199, 21, 133)
	"midnightblue":         sdl.Color{0x19, 0x19, 0x70, 0xff}, // rgb(25, 25, 112)
	"mintcream":            sdl.Color{0xf5, 0xff, 0xfa, 0xff}, // rgb(245, 255, 250)
	"mistyrose":            sdl.Color{0xff, 0xe4, 0xe1, 0xff}, // rgb(255, 228, 225)
	"moccasin":             sdl.Color{0xff, 0xe4, 0xb5, 0xff}, // rgb(255, 228, 181)
	"navajowhite":          sdl.Color{0xff, 0xde, 0xad, 0xff}, // rgb(255, 222, 173)
	"navy":                 sdl.Color{0x00, 0x00, 0x80, 0xff}, // rgb(0, 0, 128)
	"oldlace":              sdl.Color{0xfd, 0xf5, 0xe6, 0xff}, // rgb(253, 245, 230)
	"olive":                sdl.Color{0x80, 0x80, 0x00, 0xff}, // rgb(128, 128, 0)
	"olivedrab":            sdl.Color{0x6b, 0x8e, 0x23, 0xff}, // rgb(107, 142, 35)
	"orange":               sdl.Color{0xff, 0xa5, 0x00, 0xff}, // rgb(255, 165, 0)
	"orangered":            sdl.Color{0xff, 0x45, 0x00, 0xff}, // rgb(255, 69, 0)
	"orchid":               sdl.Color{0xda, 0x70, 0xd6, 0xff}, // rgb(218, 112, 214)
	"palegoldenrod":        sdl.Color{0xee, 0xe8, 0xaa, 0xff}, // rgb(238, 232, 170)
	"palegreen":            sdl.Color{0x98, 0xfb, 0x98, 0xff}, // rgb(152, 251, 152)
	"paleturquoise":        sdl.Color{0xaf, 0xee, 0xee, 0xff}, // rgb(175, 238, 238)
	"palevioletred":        sdl.Color{0xdb, 0x70, 0x93, 0xff}, // rgb(219, 112, 147)
	"papayawhip":           sdl.Color{0xff, 0xef, 0xd5, 0xff}, // rgb(255, 239, 213)
	"peachpuff":            sdl.Color{0xff, 0xda, 0xb9, 0xff}, // rgb(255, 218, 185)
	"peru":                 sdl.Color{0xcd, 0x85, 0x3f, 0xff}, // rgb(205, 133, 63)
	"pink":                 sdl.Color{0xff, 0xc0, 0xcb, 0xff}, // rgb(255, 192, 203)
	"plum":                 sdl.Color{0xdd, 0xa0, 0xdd, 0xff}, // rgb(221, 160, 221)
	"powderblue":           sdl.Color{0xb0, 0xe0, 0xe6, 0xff}, // rgb(176, 224, 230)
	"purple":               sdl.Color{0x80, 0x00, 0x80, 0xff}, // rgb(128, 0, 128)
	"red":                  sdl.Color{0xff, 0x00, 0x00, 0x00}, // rgb(255, 0, 0)
	"rosybrown":            sdl.Color{0xbc, 0x8f, 0x8f, 0xff}, // rgb(188, 143, 143)
	"royalblue":            sdl.Color{0x41, 0x69, 0xe1, 0xff}, // rgb(65, 105, 225)
	"saddlebrown":          sdl.Color{0x8b, 0x45, 0x13, 0xff}, // rgb(139, 69, 19)
	"salmon":               sdl.Color{0xfa, 0x80, 0x72, 0xff}, // rgb(250, 128, 114)
	"sandybrown":           sdl.Color{0xf4, 0xa4, 0x60, 0xff}, // rgb(244, 164, 96)
	"seagreen":             sdl.Color{0x2e, 0x8b, 0x57, 0xff}, // rgb(46, 139, 87)
	"seashell":             sdl.Color{0xff, 0xf5, 0xee, 0xff}, // rgb(255, 245, 238)
	"sienna":               sdl.Color{0xa0, 0x52, 0x2d, 0xff}, // rgb(160, 82, 45)
	"silver":               sdl.Color{0xc0, 0xc0, 0xc0, 0xff}, // rgb(192, 192, 192)
	"skyblue":              sdl.Color{0x87, 0xce, 0xeb, 0xff}, // rgb(135, 206, 235)
	"slateblue":            sdl.Color{0x6a, 0x5a, 0xcd, 0xff}, // rgb(106, 90, 205)
	"slategray":            sdl.Color{0x70, 0x80, 0x90, 0xff}, // rgb(112, 128, 144)
	"slategrey":            sdl.Color{0x70, 0x80, 0x90, 0xff}, // rgb(112, 128, 144)
	"snow":                 sdl.Color{0xff, 0xfa, 0xfa, 0xff}, // rgb(255, 250, 250)
	"springgreen":          sdl.Color{0x00, 0xff, 0x7f, 0xff}, // rgb(0, 255, 127)
	"steelblue":            sdl.Color{0x46, 0x82, 0xb4, 0xff}, // rgb(70, 130, 180)
	"tan":                  sdl.Color{0xd2, 0xb4, 0x8c, 0xff}, // rgb(210, 180, 140)
	"teal":                 sdl.Color{0x00, 0x80, 0x80, 0xff}, // rgb(0, 128, 128)
	"thistle":              sdl.Color{0xd8, 0xbf, 0xd8, 0xff}, // rgb(216, 191, 216)
	"tomato":               sdl.Color{0xff, 0x63, 0x47, 0xff}, // rgb(255, 99, 71)
	"turquoise":            sdl.Color{0x40, 0xe0, 0xd0, 0xff}, // rgb(64, 224, 208)
	"violet":               sdl.Color{0xee, 0x82, 0xee, 0xff}, // rgb(238, 130, 238)
	"wheat":                sdl.Color{0xf5, 0xde, 0xb3, 0xff}, // rgb(245, 222, 179)
	"white":                sdl.Color{0xff, 0xff, 0xff, 0xff}, // rgb(255, 255, 255)
	"whitesmoke":           sdl.Color{0xf5, 0xf5, 0xf5, 0xff}, // rgb(245, 245, 245)
	"yellow":               sdl.Color{0xff, 0xff, 0x00, 0xff}, // rgb(255, 255, 0)
	"yellowgreen":          sdl.Color{0x9a, 0xcd, 0x32, 0xff}, // rgb(154, 205, 50)
}

// Names contains the color names defined in the SVG 1.1 spec.
var Names = []string{
	"aliceblue",
	"antiquewhite",
	"aqua",
	"aquamarine",
	"azure",
	"beige",
	"bisque",
	"black",
	"blanchedalmond",
	"blue",
	"blueviolet",
	"brown",
	"burlywood",
	"cadetblue",
	"chartreuse",
	"chocolate",
	"coral",
	"cornflowerblue",
	"cornsilk",
	"crimson",
	"cyan",
	"darkblue",
	"darkcyan",
	"darkgoldenrod",
	"darkgray",
	"darkgreen",
	"darkgrey",
	"darkkhaki",
	"darkmagenta",
	"darkolivegreen",
	"darkorange",
	"darkorchid",
	"darkred",
	"darksalmon",
	"darkseagreen",
	"darkslateblue",
	"darkslategray",
	"darkslategrey",
	"darkturquoise",
	"darkviolet",
	"deeppink",
	"deepskyblue",
	"dimgray",
	"dimgrey",
	"dodgerblue",
	"firebrick",
	"floralwhite",
	"forestgreen",
	"fuchsia",
	"gainsboro",
	"ghostwhite",
	"gold",
	"goldenrod",
	"gray",
	"green",
	"greenyellow",
	"grey",
	"honeydew",
	"hotpink",
	"indianred",
	"indigo",
	"ivory",
	"khaki",
	"lavender",
	"lavenderblush",
	"lawngreen",
	"lemonchiffon",
	"lightblue",
	"lightcoral",
	"lightcyan",
	"lightgoldenrodyellow",
	"lightgray",
	"lightgreen",
	"lightgrey",
	"lightpink",
	"lightsalmon",
	"lightseagreen",
	"lightskyblue",
	"lightslategray",
	"lightslategrey",
	"lightsteelblue",
	"lightyellow",
	"lime",
	"limegreen",
	"linen",
	"magenta",
	"maroon",
	"mediumaquamarine",
	"mediumblue",
	"mediumorchid",
	"mediumpurple",
	"mediumseagreen",
	"mediumslateblue",
	"mediumspringgreen",
	"mediumturquoise",
	"mediumvioletred",
	"midnightblue",
	"mintcream",
	"mistyrose",
	"moccasin",
	"navajowhite",
	"navy",
	"oldlace",
	"olive",
	"olivedrab",
	"orange",
	"orangered",
	"orchid",
	"palegoldenrod",
	"palegreen",
	"paleturquoise",
	"palevioletred",
	"papayawhip",
	"peachpuff",
	"peru",
	"pink",
	"plum",
	"powderblue",
	"purple",
	"red",
	"rosybrown",
	"royalblue",
	"saddlebrown",
	"salmon",
	"sandybrown",
	"seagreen",
	"seashell",
	"sienna",
	"silver",
	"skyblue",
	"slateblue",
	"slategray",
	"slategrey",
	"snow",
	"springgreen",
	"steelblue",
	"tan",
	"teal",
	"thistle",
	"tomato",
	"turquoise",
	"violet",
	"wheat",
	"white",
	"whitesmoke",
	"yellow",
	"yellowgreen",
}

var (
	Aliceblue            = sdl.Color{0xf0, 0xf8, 0xff, 0xff} // rgb(240, 248, 255)
	Antiquewhite         = sdl.Color{0xfa, 0xeb, 0xd7, 0xff} // rgb(250, 235, 215)
	Aqua                 = sdl.Color{0x00, 0xff, 0xff, 0xff} // rgb(0, 255, 255)
	Aquamarine           = sdl.Color{0x7f, 0xff, 0xd4, 0xff} // rgb(127, 255, 212)
	Azure                = sdl.Color{0xf0, 0xff, 0xff, 0xff} // rgb(240, 255, 255)
	Beige                = sdl.Color{0xf5, 0xf5, 0xdc, 0xff} // rgb(245, 245, 220)
	Bisque               = sdl.Color{0xff, 0xe4, 0xc4, 0xff} // rgb(255, 228, 196)
	Black                = sdl.Color{0x00, 0x00, 0x00, 0xff} // rgb(0, 0, 0)
	Blanchedalmond       = sdl.Color{0xff, 0xeb, 0xcd, 0xff} // rgb(255, 235, 205)
	Blue                 = sdl.Color{0x00, 0x00, 0xff, 0xff} // rgb(0, 0, 255)
	Blueviolet           = sdl.Color{0x8a, 0x2b, 0xe2, 0xff} // rgb(138, 43, 226)
	Brown                = sdl.Color{0xa5, 0x2a, 0x2a, 0xff} // rgb(165, 42, 42)
	Burlywood            = sdl.Color{0xde, 0xb8, 0x87, 0xff} // rgb(222, 184, 135)
	Cadetblue            = sdl.Color{0x5f, 0x9e, 0xa0, 0xff} // rgb(95, 158, 160)
	Chartreuse           = sdl.Color{0x7f, 0xff, 0x00, 0xff} // rgb(127, 255, 0)
	Chocolate            = sdl.Color{0xd2, 0x69, 0x1e, 0xff} // rgb(210, 105, 30)
	Coral                = sdl.Color{0xff, 0x7f, 0x50, 0xff} // rgb(255, 127, 80)
	Cornflowerblue       = sdl.Color{0x64, 0x95, 0xed, 0xff} // rgb(100, 149, 237)
	Cornsilk             = sdl.Color{0xff, 0xf8, 0xdc, 0xff} // rgb(255, 248, 220)
	Crimson              = sdl.Color{0xdc, 0x14, 0x3c, 0xff} // rgb(220, 20, 60)
	Cyan                 = sdl.Color{0x00, 0xff, 0xff, 0xff} // rgb(0, 255, 255)
	Darkblue             = sdl.Color{0x00, 0x00, 0x8b, 0xff} // rgb(0, 0, 139)
	Darkcyan             = sdl.Color{0x00, 0x8b, 0x8b, 0xff} // rgb(0, 139, 139)
	Darkgoldenrod        = sdl.Color{0xb8, 0x86, 0x0b, 0xff} // rgb(184, 134, 11)
	Darkgray             = sdl.Color{0xa9, 0xa9, 0xa9, 0xff} // rgb(169, 169, 169)
	Darkgreen            = sdl.Color{0x00, 0x64, 0x00, 0xff} // rgb(0, 100, 0)
	Darkgrey             = sdl.Color{0xa9, 0xa9, 0xa9, 0xff} // rgb(169, 169, 169)
	Darkkhaki            = sdl.Color{0xbd, 0xb7, 0x6b, 0xff} // rgb(189, 183, 107)
	Darkmagenta          = sdl.Color{0x8b, 0x00, 0x8b, 0xff} // rgb(139, 0, 139)
	Darkolivegreen       = sdl.Color{0x55, 0x6b, 0x2f, 0xff} // rgb(85, 107, 47)
	Darkorange           = sdl.Color{0xff, 0x8c, 0x00, 0xff} // rgb(255, 140, 0)
	Darkorchid           = sdl.Color{0x99, 0x32, 0xcc, 0xff} // rgb(153, 50, 204)
	Darkred              = sdl.Color{0x8b, 0x00, 0x00, 0xff} // rgb(139, 0, 0)
	Darksalmon           = sdl.Color{0xe9, 0x96, 0x7a, 0xff} // rgb(233, 150, 122)
	Darkseagreen         = sdl.Color{0x8f, 0xbc, 0x8f, 0xff} // rgb(143, 188, 143)
	Darkslateblue        = sdl.Color{0x48, 0x3d, 0x8b, 0xff} // rgb(72, 61, 139)
	Darkslategray        = sdl.Color{0x2f, 0x4f, 0x4f, 0xff} // rgb(47, 79, 79)
	Darkslategrey        = sdl.Color{0x2f, 0x4f, 0x4f, 0xff} // rgb(47, 79, 79)
	Darkturquoise        = sdl.Color{0x00, 0xce, 0xd1, 0xff} // rgb(0, 206, 209)
	Darkviolet           = sdl.Color{0x94, 0x00, 0xd3, 0xff} // rgb(148, 0, 211)
	Deeppink             = sdl.Color{0xff, 0x14, 0x93, 0xff} // rgb(255, 20, 147)
	Deepskyblue          = sdl.Color{0x00, 0xbf, 0xff, 0xff} // rgb(0, 191, 255)
	Dimgray              = sdl.Color{0x69, 0x69, 0x69, 0xff} // rgb(105, 105, 105)
	Dimgrey              = sdl.Color{0x69, 0x69, 0x69, 0xff} // rgb(105, 105, 105)
	Dodgerblue           = sdl.Color{0x1e, 0x90, 0xff, 0xff} // rgb(30, 144, 255)
	Firebrick            = sdl.Color{0xb2, 0x22, 0x22, 0xff} // rgb(178, 34, 34)
	Floralwhite          = sdl.Color{0xff, 0xfa, 0xf0, 0xff} // rgb(255, 250, 240)
	Forestgreen          = sdl.Color{0x22, 0x8b, 0x22, 0xff} // rgb(34, 139, 34)
	Fuchsia              = sdl.Color{0xff, 0x00, 0xff, 0xff} // rgb(255, 0, 255)
	Gainsboro            = sdl.Color{0xdc, 0xdc, 0xdc, 0xff} // rgb(220, 220, 220)
	Ghostwhite           = sdl.Color{0xf8, 0xf8, 0xff, 0xff} // rgb(248, 248, 255)
	Gold                 = sdl.Color{0xff, 0xd7, 0x00, 0xff} // rgb(255, 215, 0)
	Goldenrod            = sdl.Color{0xda, 0xa5, 0x20, 0xff} // rgb(218, 165, 32)
	Gray                 = sdl.Color{0x80, 0x80, 0x80, 0xff} // rgb(128, 128, 128)
	Green                = sdl.Color{0x00, 0x80, 0x00, 0xff} // rgb(0, 128, 0)
	Greenyellow          = sdl.Color{0xad, 0xff, 0x2f, 0xff} // rgb(173, 255, 47)
	Grey                 = sdl.Color{0x80, 0x80, 0x80, 0xff} // rgb(128, 128, 128)
	Honeydew             = sdl.Color{0xf0, 0xff, 0xf0, 0xff} // rgb(240, 255, 240)
	Hotpink              = sdl.Color{0xff, 0x69, 0xb4, 0xff} // rgb(255, 105, 180)
	Indianred            = sdl.Color{0xcd, 0x5c, 0x5c, 0xff} // rgb(205, 92, 92)
	Indigo               = sdl.Color{0x4b, 0x00, 0x82, 0xff} // rgb(75, 0, 130)
	Ivory                = sdl.Color{0xff, 0xff, 0xf0, 0xff} // rgb(255, 255, 240)
	Khaki                = sdl.Color{0xf0, 0xe6, 0x8c, 0xff} // rgb(240, 230, 140)
	Lavender             = sdl.Color{0xe6, 0xe6, 0xfa, 0xff} // rgb(230, 230, 250)
	Lavenderblush        = sdl.Color{0xff, 0xf0, 0xf5, 0xff} // rgb(255, 240, 245)
	Lawngreen            = sdl.Color{0x7c, 0xfc, 0x00, 0xff} // rgb(124, 252, 0)
	Lemonchiffon         = sdl.Color{0xff, 0xfa, 0xcd, 0xff} // rgb(255, 250, 205)
	Lightblue            = sdl.Color{0xad, 0xd8, 0xe6, 0xff} // rgb(173, 216, 230)
	Lightcoral           = sdl.Color{0xf0, 0x80, 0x80, 0xff} // rgb(240, 128, 128)
	Lightcyan            = sdl.Color{0xe0, 0xff, 0xff, 0xff} // rgb(224, 255, 255)
	Lightgoldenrodyellow = sdl.Color{0xfa, 0xfa, 0xd2, 0xff} // rgb(250, 250, 210)
	Lightgray            = sdl.Color{0xd3, 0xd3, 0xd3, 0xff} // rgb(211, 211, 211)
	Lightgreen           = sdl.Color{0x90, 0xee, 0x90, 0xff} // rgb(144, 238, 144)
	Lightgrey            = sdl.Color{0xd3, 0xd3, 0xd3, 0xff} // rgb(211, 211, 211)
	Lightpink            = sdl.Color{0xff, 0xb6, 0xc1, 0xff} // rgb(255, 182, 193)
	Lightsalmon          = sdl.Color{0xff, 0xa0, 0x7a, 0xff} // rgb(255, 160, 122)
	Lightseagreen        = sdl.Color{0x20, 0xb2, 0xaa, 0xff} // rgb(32, 178, 170)
	Lightskyblue         = sdl.Color{0x87, 0xce, 0xfa, 0xff} // rgb(135, 206, 250)
	Lightslategray       = sdl.Color{0x77, 0x88, 0x99, 0xff} // rgb(119, 136, 153)
	Lightslategrey       = sdl.Color{0x77, 0x88, 0x99, 0xff} // rgb(119, 136, 153)
	Lightsteelblue       = sdl.Color{0xb0, 0xc4, 0xde, 0xff} // rgb(176, 196, 222)
	Lightyellow          = sdl.Color{0xff, 0xff, 0xe0, 0xff} // rgb(255, 255, 224)
	Lime                 = sdl.Color{0x00, 0xff, 0x00, 0xff} // rgb(0, 255, 0)
	Limegreen            = sdl.Color{0x32, 0xcd, 0x32, 0xff} // rgb(50, 205, 50)
	Linen                = sdl.Color{0xfa, 0xf0, 0xe6, 0xff} // rgb(250, 240, 230)
	Magenta              = sdl.Color{0xff, 0x00, 0xff, 0xff} // rgb(255, 0, 255)
	Maroon               = sdl.Color{0x80, 0x00, 0x00, 0xff} // rgb(128, 0, 0)
	Mediumaquamarine     = sdl.Color{0x66, 0xcd, 0xaa, 0xff} // rgb(102, 205, 170)
	Mediumblue           = sdl.Color{0x00, 0x00, 0xcd, 0xff} // rgb(0, 0, 205)
	Mediumorchid         = sdl.Color{0xba, 0x55, 0xd3, 0xff} // rgb(186, 85, 211)
	Mediumpurple         = sdl.Color{0x93, 0x70, 0xdb, 0xff} // rgb(147, 112, 219)
	Mediumseagreen       = sdl.Color{0x3c, 0xb3, 0x71, 0xff} // rgb(60, 179, 113)
	Mediumslateblue      = sdl.Color{0x7b, 0x68, 0xee, 0xff} // rgb(123, 104, 238)
	Mediumspringgreen    = sdl.Color{0x00, 0xfa, 0x9a, 0xff} // rgb(0, 250, 154)
	Mediumturquoise      = sdl.Color{0x48, 0xd1, 0xcc, 0xff} // rgb(72, 209, 204)
	Mediumvioletred      = sdl.Color{0xc7, 0x15, 0x85, 0xff} // rgb(199, 21, 133)
	Midnightblue         = sdl.Color{0x19, 0x19, 0x70, 0xff} // rgb(25, 25, 112)
	Mintcream            = sdl.Color{0xf5, 0xff, 0xfa, 0xff} // rgb(245, 255, 250)
	Mistyrose            = sdl.Color{0xff, 0xe4, 0xe1, 0xff} // rgb(255, 228, 225)
	Moccasin             = sdl.Color{0xff, 0xe4, 0xb5, 0xff} // rgb(255, 228, 181)
	Navajowhite          = sdl.Color{0xff, 0xde, 0xad, 0xff} // rgb(255, 222, 173)
	Navy                 = sdl.Color{0x00, 0x00, 0x80, 0xff} // rgb(0, 0, 128)
	Oldlace              = sdl.Color{0xfd, 0xf5, 0xe6, 0xff} // rgb(253, 245, 230)
	Olive                = sdl.Color{0x80, 0x80, 0x00, 0xff} // rgb(128, 128, 0)
	Olivedrab            = sdl.Color{0x6b, 0x8e, 0x23, 0xff} // rgb(107, 142, 35)
	Orange               = sdl.Color{0xff, 0xa5, 0x00, 0xff} // rgb(255, 165, 0)
	Orangered            = sdl.Color{0xff, 0x45, 0x00, 0xff} // rgb(255, 69, 0)
	Orchid               = sdl.Color{0xda, 0x70, 0xd6, 0xff} // rgb(218, 112, 214)
	Palegoldenrod        = sdl.Color{0xee, 0xe8, 0xaa, 0xff} // rgb(238, 232, 170)
	Palegreen            = sdl.Color{0x98, 0xfb, 0x98, 0xff} // rgb(152, 251, 152)
	Paleturquoise        = sdl.Color{0xaf, 0xee, 0xee, 0xff} // rgb(175, 238, 238)
	Palevioletred        = sdl.Color{0xdb, 0x70, 0x93, 0xff} // rgb(219, 112, 147)
	Papayawhip           = sdl.Color{0xff, 0xef, 0xd5, 0xff} // rgb(255, 239, 213)
	Peachpuff            = sdl.Color{0xff, 0xda, 0xb9, 0xff} // rgb(255, 218, 185)
	Peru                 = sdl.Color{0xcd, 0x85, 0x3f, 0xff} // rgb(205, 133, 63)
	Pink                 = sdl.Color{0xff, 0xc0, 0xcb, 0xff} // rgb(255, 192, 203)
	Plum                 = sdl.Color{0xdd, 0xa0, 0xdd, 0xff} // rgb(221, 160, 221)
	Powderblue           = sdl.Color{0xb0, 0xe0, 0xe6, 0xff} // rgb(176, 224, 230)
	Purple               = sdl.Color{0x80, 0x00, 0x80, 0xff} // rgb(128, 0, 128)
	Red                  = sdl.Color{0xff, 0x00, 0x00, 0xff} // rgb(255, 0, 0)
	Rosybrown            = sdl.Color{0xbc, 0x8f, 0x8f, 0xff} // rgb(188, 143, 143)
	Royalblue            = sdl.Color{0x41, 0x69, 0xe1, 0xff} // rgb(65, 105, 225)
	Saddlebrown          = sdl.Color{0x8b, 0x45, 0x13, 0xff} // rgb(139, 69, 19)
	Salmon               = sdl.Color{0xfa, 0x80, 0x72, 0xff} // rgb(250, 128, 114)
	Sandybrown           = sdl.Color{0xf4, 0xa4, 0x60, 0xff} // rgb(244, 164, 96)
	Seagreen             = sdl.Color{0x2e, 0x8b, 0x57, 0xff} // rgb(46, 139, 87)
	Seashell             = sdl.Color{0xff, 0xf5, 0xee, 0xff} // rgb(255, 245, 238)
	Sienna               = sdl.Color{0xa0, 0x52, 0x2d, 0xff} // rgb(160, 82, 45)
	Silver               = sdl.Color{0xc0, 0xc0, 0xc0, 0xff} // rgb(192, 192, 192)
	Skyblue              = sdl.Color{0x87, 0xce, 0xeb, 0xff} // rgb(135, 206, 235)
	Slateblue            = sdl.Color{0x6a, 0x5a, 0xcd, 0xff} // rgb(106, 90, 205)
	Slategray            = sdl.Color{0x70, 0x80, 0x90, 0xff} // rgb(112, 128, 144)
	Slategrey            = sdl.Color{0x70, 0x80, 0x90, 0xff} // rgb(112, 128, 144)
	Snow                 = sdl.Color{0xff, 0xfa, 0xfa, 0xff} // rgb(255, 250, 250)
	Springgreen          = sdl.Color{0x00, 0xff, 0x7f, 0xff} // rgb(0, 255, 127)
	Steelblue            = sdl.Color{0x46, 0x82, 0xb4, 0xff} // rgb(70, 130, 180)
	Tan                  = sdl.Color{0xd2, 0xb4, 0x8c, 0xff} // rgb(210, 180, 140)
	Teal                 = sdl.Color{0x00, 0x80, 0x80, 0xff} // rgb(0, 128, 128)
	Thistle              = sdl.Color{0xd8, 0xbf, 0xd8, 0xff} // rgb(216, 191, 216)
	Tomato               = sdl.Color{0xff, 0x63, 0x47, 0xff} // rgb(255, 99, 71)
	Turquoise            = sdl.Color{0x40, 0xe0, 0xd0, 0xff} // rgb(64, 224, 208)
	Violet               = sdl.Color{0xee, 0x82, 0xee, 0xff} // rgb(238, 130, 238)
	Wheat                = sdl.Color{0xf5, 0xde, 0xb3, 0xff} // rgb(245, 222, 179)
	White                = sdl.Color{0xff, 0xff, 0xff, 0xff} // rgb(255, 255, 255)
	Whitesmoke           = sdl.Color{0xf5, 0xf5, 0xf5, 0xff} // rgb(245, 245, 245)
	Yellow               = sdl.Color{0xff, 0xff, 0x00, 0xff} // rgb(255, 255, 0)
	Yellowgreen          = sdl.Color{0x9a, 0xcd, 0x32, 0xff} // rgb(154, 205, 50)
)
